cloudwego/dynamicgo

README.md
go.mod
go.sum

build
en: update go mod dependency and requirements doc
zh: 更新 go mod 依赖，添加 requirements 文档

build: update go mod dependency and requirements

---

conv/j2t/conv_test.go
conv/j2t/impl.go
conv/t2j/conv_test.go
conv/t2j/impl.go
testdata/idl/example3.thrift
testdata/kitex_gen/example3/example3.go
testdata/kitex_gen/example3/k-example3.go

feat
en: (conv) support convert scalar types of arguments
zh: 协议转换支持简单类型参数

feat:(conv) support convert scalar types of arguments

---

conv/j2t/conv_test.go
conv/j2t/http_conv.go
conv/j2t/impl.go
http/http.go
http/http_test.go
internal/util_test/req.go
thrift/annotation/http_mapping.go

refactor
en: rename methods on `RequestGetter` to avoid conflicts
zh: 重命名`RequestGetter`以避免命名冲突

refactor:(http) rename methods on `RequestGetter` to avoid conflicts

---

conv/t2j/http_conv.go
thrift/binary.go
thrift/binary_test.go
thrift/generic/README.md
thrift/generic/error.go
thrift/generic/node.go
thrift/generic/option.go
thrift/generic/path.go
thrift/generic/path_test.go

feat
en:  add more utility APIs for thrift/generic
zh: 为 thrift/genenric 包添加更多工具 API

feat:(thrift/genenric) add more utility APIs

---

testdata/idl/example.thrift
testdata/idl/ref.thrift
thrift/idl.go
thrift/idl_test.go

fix
en: fix dead loop introduced by thrift IDL file cycle-referring
zh(optional): 修复 thrift IDL 文件循环引用导致解析时死循环问题

fix: dead loop introduced by thrift IDL file cycle-referring

---

conv/api.go
conv/j2t/impl.go
conv/t2j/conv_test.go
conv/t2j/conv_timing_test.go
conv/t2j/impl.go
internal/primitive/impl.go
meta/const.go
testdata/idl/example3.thrift
testdata/kitex_gen/example3/example3.go
testdata/kitex_gen/example3/k-example3.go
thrift/binary.go
thrift/example_test.go

refactor
en: 
- refactor http-value encoding logics on `conv`
- add conv option `UseKitexHttpEncoding` to be compatible with `kitex/geneneric`
zh(optional): 
- 重构`conv`包内 HTTP 值编码逻辑
- 添加 conv 选项 `UseKitexHttpEncoding` 以和 kitex/generic 兼容

refactor(conv): http-value encoding logics

---

internal/json/encoding.go

fix
en: remove redundant print in `json.EncodeString()`
zh(optional):

fix: redundant print

---

thrift/generic/option.go
thrift/generic/path.go
thrift/generic/path_test.go

feat
en:
zh(optional): 
- 优化“DescriptorToPathNode()”函数支持简单类型赋零值
- 并且同时初始化map/list。
- 添加函数“PathNodeTointerface()"方便debug

feat: upgrade `DescriptorToPathNode` API

---

thrift/generic/option.go
thrift/generic/path.go
thrift/generic/path_test.go

feat
en: add this option to allow user to control if generate zero value for required or default fields when calling `DescriptorToPathNode()`
zh(optional):

feat:(thrift/generic) add option `DescriptorToPathNodeWriteOptional` 

---

.gitmodules
conv/j2p/api_amd64.go
go.mod
go.sum
internal/json/api_amd64.go

chore
en: chore: immigrate some dependencies to 'cloudwego'
zh(optional): 将部分依赖迁移到 cloudwego

chore: immigrate some dependencies to 'cloudwego'

---

go.mod
go.sum

chore: update kitex to v0.9.3-rc

---

go.mod
go.sum
thrift/annotation.go
thrift/idl.go
thrift/idl_test.go

feat
en:
zh(optional): 支持将IDL命名空间放入 Descriptor 的注解中

feat:(thrift) support putting IDL name-space into Descriptor's annotations

---

conv/j2p/conv_test.go
conv/j2p/decode.go
conv/j2p/impl.go
go.mod
go.sum

fix:(conv/j2p) support skip unknow fields

---

proto/descriptor.go
proto/idl.go
proto/idl_test.go

feat(proto): support streaming mode for proto

---

.github/workflows/benchmark-linux-x64.yml
.github/workflows/push-check-linux-compat.yml
.github/workflows/push-check-linux-x64.yml

chore
更新 ci 的 go版本号，minimum go1.17, benchmark go1.19
en:
zh(optional):

chore: ci minimum go1.17, benchmark go1.19

---

conv/j2t/impl.go

fix
en: use `runtime.KeepAlive` to keep input json string alive, in case of it got freed by GC
zh(optional):

fix:(j2t) keep input memory alive

---

go.mod
go.sum
testdata/test/go.mod
testdata/test/go.sum

chore: update protobuf version in go mod for security
en: chore: update protobuf version in go mod for security
zh(optional):  修复protobuf 1.28.1因安全漏洞而版本升级后带来的依赖问题。

chore: update protobuf version in go mod for security

---

.github/workflows/push-check-linux-x64.yml
internal/json/decode.go
internal/json/encoding.go
internal/rt/fastmem.go

fix: avoid boundary ptr

---

thrift/idl.go
thrift/idl_test.go

fix(thrift): support both relative and absolute check for idl includes parse to make it compatible with generation tool

---

thrift/idl.go

fix(thrift): fix the logic of includes search

---

thrift/idl.go
thrift/idl_test.go

fix(thrift): 修复idl 匹配 include 时不是绝对路径优先的问题，与kitex/generic对齐
en: introduced by #90 
zh(optional):

fix(thrift): absolute-paths were not prioritized when IDL matches includes
